set -g prefix `
unbind C-b
bind-key ` last-window
bind ` send-prefix

set -g history-limit 1000000

set -s set-clipboard on

# mouse scrolling
set -g mouse on

# Start windows and panes index at 1, not 0.
set -g base-index 1
setw -g pane-base-index 1

# Ensure window index numbers get reordered on delete.
set -g renumber-windows on

if-shell '[ $(uname) == "Darwin" ]' {
  set -s copy-command 'pbcopy'
}

if-shell '[ $(uname) == "Linux" ] && command -v xsel &> /dev/null ' {
  set -s copy-command 'xsel --input'
}

if-shell '[ $(uname) == "Linux" ] && command -v xclip &> /dev/null ' {
  set -s copy-command 'xclip -selection clipboard -in'
}

# Use vim keybindings in copy mode
set -g mode-keys vi

#bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel xclip

#https://til.hashrocket.com/posts/d4d3c1fea6-quickly-edit-and-reload-tmux-configuration                                             
bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"
bind-key M split-window -h "vim ~/.tmux.conf"

#Synchronize panes
bind-key X set-window-option synchronize-panes\; display-message "synchronize-panes is now #{?pane_synchronized,on,off}"

# Create new panes in the same working directory
# https://github.com/tmux/tmux/wiki/Recipes#create-new-panes-in-the-same-working-directory
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -hc "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
